# Generated by Django 3.1.4 on 2020-12-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='cpf',
            name='funcionario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='funcionario',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.Funcionario'),
        ),
    ]
