# Generated by Django 3.1.4 on 2020-12-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20201227_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
